### ISSUE TITLE
Issue with permalink when clicking post title on 1UP Site

### ISSUE THREAD

**Issue by tobias-g1** [therealFlauwy/1UP#26]
#### Expected behavior
You should be able to click on any of the TITLES that are located on any of the posts which have received a 1up on any of the tabs (Now, today, yesterday, all time) and it should open the relevant post on utopian.io

#### Actual behavior
If you click on any of the titles other than the post that is currently first the permalink for the post will always be the post that is first on the tab you're currently using, thus not taking you to the correct post except when you wish to go to the currently ranked first post. 

#### How to reproduce
1. Go to http://www.utopian-1up.com/now 
2. Click on the title of the post which is currently ranked first, a new window will appear and you will be shown the post ranked first. Note the permalink that appears when the posts is loaded. 
3. Go back to http://www.utopian-1up.com/now and click on the the title of the post which appears 2nd, 3rd or 4th (It doesn't matter)
4. A new window will open which will try to open the post, it will populate the username within the URL correctly however it will not populate the permalink correctly and instead will try to populate the url with permalink with the link that is currently first.

Note: I noted the permalink as the following part of the URL, I have marked it in bold. I have also remove the username of that the post due to this being a problem on a previous post

https://utopian.io/utopian-io/@some-generic-username/**adding-approved-rejected-stats-showing-friends-vp-rep-to-utopian-moderator-chrome-extension**

1. Browser: Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit)) 
2. Operating system: MacOS HighSierra Version 10.13

#### Recording Of The Bug
A recording of the bug can be found here: https://d.tube/#!/v/tobias-g/mai79t8z

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/issue-with-permalink-when-clicking-post-title-on-1up-site">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by therealFlauwy** [comment]
fixed
