### ISSUE TITLE
cards that have been upvoted by utopian bot for days are still available on queue to receive 1up

### ISSUE THREAD

**Issue by kodeblacc** [therealFlauwy/1UP#27]
#### Expected behavior
I expected that with the way 1up was designed, after a post has been upvoted by utopian bot and is not legible for 1up vote, the card should not be available on queue.
#### Actual behavior
Even when the uotpian bot has upvoted a post the card still remains in the queue to receive 1up which wouldn't be possible, thereby constituting a long queue and giving inaccurate information. 
#### How to reproduce
- install steemplus extension on PC google chrome is easier (not really necessary)
- goto [website](http://www.utopian-1up.com/now)
- check out the list of cards some have been voted for and still existing on the queue( example is my card, COOL FEATURES NEEDED IN PRODIGAL MUSIC PLAYER) it has been upvoted by the utopian bot but its still on queue
<hr>

* Browser: google chrome
* Operating system: windows 7
* Software version: 2.4.0.1

#### Recording Of The Bug
https://youtu.be/h-5eFxBLsQY
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/cards-that-have-been-upvoted-by-utopian-bot-for-days-are-still-available-on-queue-to-receive-1up">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by therealFlauwy** [comment]
fixed
