### ISSUE TITLE
1up vote not working. says I can only vote a user once per day when I haven't voted the user at all and only 1 card is on the queue to receive 1up against many other cards that have been in queue.

### ISSUE THREAD

**Issue by kodeblacc** [therealFlauwy/1UP#29]
#### Expected behavior
I expected to be able to give 1up votes to people I haven't voted for within the space of a day. I also expected to see the number of cards waiting in queue to receive upvote from 1up curation trail.
#### Actual behavior
On clicking the 1up button, Iget the message that I can only vote the user once per day. On the 1up website it displays only one card as at the time of posting and also I'm unable to give 1up votes to other users.
#### How to reproduce
- install steemplus extension (works better on google chrome)
- login to the extension, to make the 1up vote icon available (rep must be 45 and above)
- goto utopian.io and select a post to give 1up vote and it says that I can't give upvote twice in less than 24hrs
- on the 1up [site](http://www.utopian-1up.com/now) only one card is on queue as at the time I was making this post, which is an anomaly

* Browser: google chrome 
* Operating system: windows 7 professional 

#### Recording Of The Bug
https://youtu.be/gVm2c_jgKVg
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/1up-vote-not-working-says-i-can-only-vote-a-user-once-per-day-when-i-haven-t-voted-the-user-at-all">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by therealFlauwy** [comment]
Fixed
