### ISSUE TITLE
After I won a voting round on 1up queue I wasn't upvoted by the curation trail.

### ISSUE THREAD

**Issue by kodeblacc** [therealFlauwy/1UP#35]
#### Expected behavior
I expected that after winning the round on the queue to receive an upvote from the 1up curation trail I will be upvoted.

#### Actual behavior
After I won the voting round I was not upvoted by the trail.

#### How to reproduce
Normally this requires the steemplus extension installed on your browser to be able to give 1up votes on the utopian website.

After the 1up vote is given, the user that is voted is subjected to waiting on a queue that is time based.

After winning the voting round I didn't get upvoted by the trail.

* Browser: google chrome
* Operating system: windows 7 profesional

#### Recording Of The Bug
https://youtu.be/7UyYWh8-mwA

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/5ahdg3-after-i-won-a-voting-round-on-1up-queue-i-wasn-t-upvoted-by-the-curation-trail">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by imwatsi** [comment]
The link to the post in question: https://utopian.io/utopian-io/@kodeblacc/on-my-pc-when-i-paste-a-copied-text-the-text-box-moves

**Comment by kodeblacc** [comment]
Yes that is the link
